module.exports = [
    {
        name: 'Advanced Night Repair Synchronized Multi-Recovery Complex Serum',
        brand: 'Estee Lauder',
        category: 'serum',
        originPrice: '105',
        ml: '50',
        lowestPrice: '73.5',
        lowestPerMl: '1.47',
    },
    {
        name: 'Micro Essence Treatment Lotion with Bio-Ferment',
        brand: 'Estee Lauder',
        category: 'lotion',
        originPrice: '122',
        ml: '200',
        lowestPrice: '85.4',
        lowestPerMl: '0.427',
    },
    {
        name: 'Mini Revitalizing Supreme+ Youth Power Creme Moisturizer',
        brand: 'Estee Lauder',
        category: 'moisturizer',
        originPrice: '64',
        ml: '30',
        lowestPrice: '44.8',
        lowestPerMl: '1.493',
    },
    {
        name: 'Advanced Genifique Radiance Boosting Face Serum',
        brand: 'Lancome',
        category: 'serum',
        originPrice: '109',
        ml: '50',
        lowestPrice: '54.5',
        lowestPerMl: '1.09',
    },
    {
        name: 'Absolue Soft Cream Revitalizing & Brightening Moisturizer',
        brand: 'Lancome',
        category: 'moisturizer',
        originPrice: '131',
        ml: '30',
        lowestPrice: '65.5',
        lowestPerMl: '2.183',
    },
    {
        name: 'Tonique Confort Hydrating & Toning Duo',
        brand: 'Lancome',
        category: 'lotion',
        originPrice: '49',
        ml: '200',
        lowestPrice: '24.5',
        lowestPerMl: '0.1225',
    },
    {
        name: 'Dramatically Different Moisturizing Lotion+',
        brand: 'Clinique',
        category: 'lotion',
        originPrice: '32.5',
        ml: '125',
        lowestPrice: '16.25',
        lowestPerMl: '0.13',
    },
    {
        name: 'Even Better Clinical Radical Dark Spot Corrector + Interrupter Serum',
        brand: 'Clinique',
        category: 'serum',
        originPrice: '85',
        ml: '50',
        lowestPrice: '42.5',
        lowestPerMl: '0.85',
    },
    {
        name: 'Moisture Surge 100H Auto-Replenishing Hydrator Moisturizer',
        brand: 'Clinique',
        category: 'moisturizer',
        originPrice: '79',
        ml: '125',
        lowestPrice: '39.5',
        lowestPerMl: '0.316',
    },
    {
        name: 'The Moisturizing Soft Cream Moisturizer',
        brand: 'Lamer',
        category: 'moisturizer',
        originPrice: '545',
        ml: '100',
        lowestPrice: '381.5',
        lowestPerMl: '3.815',
    },
    {
        name: 'The Treatment Lotion',
        brand: 'Lamer',
        category: 'lotion',
        originPrice: '180',
        ml: '150',
        lowestPrice: '126',
        lowestPerMl: '0.84',
    },

];